<a href="https://colab.research.google.com/github/Sushmithaa-Pandian/NLP/blob/main/FakeNews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [2]:
import pandas as pd
df=pd.read_csv('/content/gdrive/MyDrive/train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:

df=df.dropna()
X=df.drop('label',axis=1)
y=df['label']

In [4]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [6]:
voc_size=4000

In [7]:
messages=X.copy()

In [8]:
messages.reset_index(inplace=True)

In [9]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [10]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [11]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [12]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [13]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[2354, 3497, 3039, 2965, 351, 3611, 529, 3447, 2493, 1131],
 [1320, 3455, 1434, 2817, 3474, 2728, 1541],
 [1653, 963, 1342, 3798],
 [2685, 407, 3235, 2449, 2047, 4],
 [2354, 3474, 1499, 3496, 1149, 2619, 3474, 193, 2337, 2161],
 [1755,
  2515,
  1180,
  3596,
  1306,
  3392,
  1145,
  1790,
  1246,
  3140,
  2885,
  2129,
  565,
  1174,
  1541],
 [2620, 2144, 2683, 2776, 452, 1235, 2047, 3648, 850, 2245, 920],
 [2735, 2400, 2427, 1914, 1208, 399, 3392, 3017, 850, 2245, 920],
 [1582, 3998, 1827, 1645, 138, 840, 236, 2003, 3392, 1494],
 [3173, 941, 2960, 1913, 1519, 3388, 3104, 1424],
 [377, 1738, 1323, 2311, 1635, 2717, 1545, 615, 3540, 1794, 1272],
 [2449, 1411, 351, 840, 3392, 1208],
 [2591, 1013, 1487, 2409, 92, 3824, 793, 3562, 3230],
 [2577, 3720, 3247, 3228, 3673, 258, 3883, 850, 2245, 920],
 [3727, 2368, 2386, 1448, 2195, 850, 2245, 920],
 [2466, 2355, 2881, 2125, 3725, 2550, 2404, 3154, 3149, 2575],
 [995, 3191, 3455],
 [2202, 3067, 3190, 1502, 3392, 3302, 549, 1541],
 [1640, 4

In [14]:
sent_length=15
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3447 2493 1131]
 [   0    0    0 ... 3474 2728 1541]
 [   0    0    0 ...  963 1342 3798]
 ...
 [   0    0    0 ...  850 2245  920]
 [   0    0    0 ... 2549 2121 2625]
 [   0    0    0 ... 2758 2292 3091]]


In [15]:
from tensorflow.keras.layers import Dropout
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 15, 40)            160000    
                                                                 
 dropout (Dropout)           (None, 15, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 216,501
Trainable params: 216,501
Non-trainable params: 0
_________________________________________________________________


In [16]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [18]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=32)

Epoch 1/10
383/383 [==============================] - 22s 46ms/step - loss: 0.2821 - accuracy: 0.8696 - val_loss: 0.2043 - val_accuracy: 0.9137
Epoch 2/10
383/383 [==============================] - 8s 21ms/step - loss: 0.1394 - accuracy: 0.9461 - val_loss: 0.1990 - val_accuracy: 0.9203
Epoch 3/10
383/383 [==============================] - 8s 22ms/step - loss: 0.1031 - accuracy: 0.9617 - val_loss: 0.2076 - val_accuracy: 0.9158
Epoch 4/10
383/383 [==============================] - 9s 23ms/step - loss: 0.0716 - accuracy: 0.9753 - val_loss: 0.2518 - val_accuracy: 0.9158
Epoch 5/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0531 - accuracy: 0.9810 - val_loss: 0.2729 - val_accuracy: 0.9138
Epoch 6/10
383/383 [==============================] - 9s 23ms/step - loss: 0.0406 - accuracy: 0.9865 - val_loss: 0.2984 - val_accuracy: 0.9102
Epoch 7/10
383/383 [==============================] - 7s 19ms/step - loss: 0.0293 - accuracy: 0.9906 - val_loss: 0.3836 - val_accuracy: 0.913

In [23]:
eval_result = model.evaluate(X_test, y_test)
print(eval_result)

189/189 [==============================] - 1s 5ms/step - loss: 0.4652 - accuracy: 0.9148
[0.4652037024497986, 0.9148301482200623]


In [25]:
y_predicted=model.predict(X_test)

189/189 [==============================] - 2s 11ms/step


In [28]:
y_predicted=(y_predicted>=0.5)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92      3419
           1       0.88      0.93      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.92      0.91      6035
weighted avg       0.92      0.91      0.92      6035



In [31]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predicted))


[[3083  336]
 [ 178 2438]]


In [32]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_predicted)
print(acc)

0.9148301574150787
